### PR TITLE
Add Comment section to UI translation

### PR DESCRIPTION
**Pull request by florentdordaquy**
Hello, 

I propose a modified structure for the translation files, including a comment section for every parent key.
You can fill it by anyhthing you want if needed.

Thanks

### CODE REVIEW

**Review by RaenonX — COMMENTED** [review]
Could you help me changing the comment content to 
`TODO: Add comments`

Good to merge after these 2 are done.

**Comment by florentdordaquy** [comment]
> Could you help me changing the comment content to `TODO: Add comments`
> 
> Good to merge after these 2 are done.

Done

**Review by RaenonX — APPROVED** [review]

**Comment by RaenonX** [comment]
Eh....see if you rebase onto the current `main`? Or it is?
image

**Comment by florentdordaquy** [comment]
> Eh....see if you rebase onto the current `main`? Or it is? image

It's not, let me fix that

**Comment by RaenonX** [comment]
> > Eh....see if you rebase onto the current `main`? Or it is?
> 
> It's not, let me fix that

Don't forget to re-open

**Pull request closed without merging**
